services:
  # Socket Server
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./server:/app
    ports:
      - "1337:1337"
    environment:
      - PORT=1337

  # Client
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
      args:
        - VITE_SOCKET_URL=ws://127.0.0.1:1337
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
